-- =============================================
-- オボエ（漢字学習Webアプリ）テーブル定義スクリプト
-- DB: Oracle Database
-- 作成日: 2026-02-22
-- =============================================
-- テーブル構成:
--   1. account   : 会員情報
--   2. kanji     : 漢字データ
--   3. kanji_log : 学習ログ（出席判定兼用）
--
-- 出席の判定方法:
--   kanji_log にその日付のレコードが1件以上 → 出席とみなす
--   ※ attendance テーブルは使用しない
-- =============================================


-- =============================================
-- 0. 既存テーブルの削除（依存関係の逆順）
-- =============================================
DROP TABLE kanji_log CASCADE CONSTRAINTS PURGE;
DROP TABLE kanji     CASCADE CONSTRAINTS PURGE;
DROP TABLE account   CASCADE CONSTRAINTS PURGE;


-- =============================================
-- 1. 会員テーブル（account）
-- =============================================
-- accID     : 内部主キー（自動採番）
-- userID    : ログインID（メールアドレス、UNIQUE）
-- userPW1   : パスワード
-- userPW2   : パスワード確認
-- email     : メールアドレス
-- phone     : 電話番号
-- nickname  : ニックネーム（UNIQUE）
-- attendance: カラムは存在するが、実際の出席はkanji_logで判定
-- regDate   : 登録日時（自動設定 / カレンダーのグレーアウト基準）
-- =============================================
CREATE TABLE account (
    accID      NUMBER        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userID     VARCHAR2(50)  NOT NULL UNIQUE,
    userPW1    VARCHAR2(100) NOT NULL,
    userPW2    VARCHAR2(100) NOT NULL,
    email      VARCHAR2(100) NOT NULL,
    phone      VARCHAR2(20),
    nickname   VARCHAR2(50)  NOT NULL UNIQUE,
    attendance VARCHAR2(50),
    regDate    TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL
);


-- =============================================
-- 2. 漢字テーブル（kanji）
-- =============================================
-- kanjiindex         : 漢字識別コード（例: N5-001）
-- kanji              : 漢字1文字
-- onyomi1~3          : 音読み（最大3つ）
-- kunyomi1~3         : 訓読み（最大3つ）
-- korean_meaning     : 韓国語の意味
-- meaning_description: 意味の説明
-- example1~3         : 用例（最大3つ）
-- jlpt_level         : JLPTレベル（N5〜N1）
-- sector             : セクター番号
-- index_num          : セクター内の順番
-- created_at         : 作成日時（自動設定）
-- updated_at         : 更新日時（トリガーで自動更新）
-- =============================================
CREATE TABLE kanji (
    kanjiID             NUMBER        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kanjiindex          VARCHAR2(20)  NOT NULL UNIQUE,
    kanji               NCHAR(1)      NOT NULL,
    onyomi1             VARCHAR2(10),
    onyomi2             VARCHAR2(10),
    onyomi3             VARCHAR2(10),
    kunyomi1            VARCHAR2(30),
    kunyomi2            VARCHAR2(30),
    kunyomi3            VARCHAR2(30),
    korean_meaning      VARCHAR2(20)  NOT NULL,
    meaning_description VARCHAR2(100),
    example1            VARCHAR2(100),
    example2            VARCHAR2(100),
    example3            VARCHAR2(100),
    jlpt_level          VARCHAR2(2)   NOT NULL,
    sector              NUMBER        NOT NULL,
    index_num           NUMBER        NOT NULL,
    created_at          TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    updated_at          TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,

    CONSTRAINT ck_kanji_jlpt CHECK (jlpt_level IN ('N5', 'N4', 'N3', 'N2', 'N1'))
);

INSERT INTO kanji (kanjiindex, kanji, onyomi1, onyomi2, onyomi3, kunyomi1, kunyomi2, kunyomi3,
                   korean_meaning, meaning_description, example1, example2, example3,
                   jlpt_level, sector, index_num)
VALUES ('N5-001', '日', 'ニチ', 'ジツ', NULL, 'ひ', 'か', NULL,
        '해, 날', '해, 날짜를 나타내는 한자', '日本(にほん)', '毎日(まいにち)', '日曜日(にちようび)',
        'N5', 1, 1);

INSERT INTO kanji (kanjiindex, kanji, onyomi1, onyomi2, onyomi3, kunyomi1, kunyomi2, kunyomi3,
                   korean_meaning, meaning_description, example1, example2, example3,
                   jlpt_level, sector, index_num)
VALUES ('N5-002', '月', 'ゲツ', 'ガツ', NULL, 'つき', NULL, NULL,
        '달, 월', '달, 월을 나타내는 한자', '月曜日(げつようび)', '一月(いちがつ)', '今月(こんげつ)',
        'N5', 1, 2);

INSERT INTO kanji (kanjiindex, kanji, onyomi1, onyomi2, onyomi3, kunyomi1, kunyomi2, kunyomi3,
                   korean_meaning, meaning_description, example1, example2, example3,
                   jlpt_level, sector, index_num)
VALUES ('N5-003', '火', 'カ', NULL, NULL, 'ひ', NULL, NULL,
        '불', '불을 나타내는 한자', '火曜日(かようび)', '火事(かじ)', '花火(はなび)',
        'N5', 1, 3);

INSERT INTO kanji (kanjiindex, kanji, onyomi1, onyomi2, onyomi3, kunyomi1, kunyomi2, kunyomi3,
                   korean_meaning, meaning_description, example1, example2, example3,
                   jlpt_level, sector, index_num)
VALUES ('N5-004', '水', 'スイ', NULL, NULL, 'みず', NULL, NULL,
        '물', '물을 나타내는 한자', '水曜日(すいようび)', '水(みず)', '水泳(すいえい)',
        'N5', 1, 4);

INSERT INTO kanji (kanjiindex, kanji, onyomi1, onyomi2, onyomi3, kunyomi1, kunyomi2, kunyomi3,
                   korean_meaning, meaning_description, example1, example2, example3,
                   jlpt_level, sector, index_num)
VALUES ('N5-005', '木', 'モク', 'ボク', NULL, 'き', NULL, NULL,
        '나무', '나무를 나타내는 한자', '木曜日(もくようび)', '木(き)', '木造(もくぞう)',
        'N5', 1, 5);

INSERT INTO kanji (kanjiindex, kanji, onyomi1, onyomi2, onyomi3, kunyomi1, kunyomi2, kunyomi3,
                   korean_meaning, meaning_description, example1, example2, example3,
                   jlpt_level, sector, index_num)
VALUES ('N5-006', '金', 'キン', 'コン', NULL, 'かね', 'かな', NULL,
        '쇠, 돈', '금, 쇠, 돈을 나타내는 한자', '金曜日(きんようび)', '金(かね)', '料金(りょうきん)',
        'N5', 1, 6);

INSERT INTO kanji (kanjiindex, kanji, onyomi1, onyomi2, onyomi3, kunyomi1, kunyomi2, kunyomi3,
                   korean_meaning, meaning_description, example1, example2, example3,
                   jlpt_level, sector, index_num)
VALUES ('N5-007', '土', 'ド', 'ト', NULL, 'つち', NULL, NULL,
        '흙', '흙, 토요일을 나타내는 한자', '土曜日(どようび)', '土地(とち)', '国土(こくど)',
        'N5', 1, 7);

INSERT INTO kanji (kanjiindex, kanji, onyomi1, onyomi2, onyomi3, kunyomi1, kunyomi2, kunyomi3,
                   korean_meaning, meaning_description, example1, example2, example3,
                   jlpt_level, sector, index_num)
VALUES ('N5-008', '年', 'ネン', NULL, NULL, 'とし', NULL, NULL,
        '해, 년', '년도, 해를 나타내는 한자', '今年(ことし)', '去年(きょねん)', '来年(らいねん)',
        'N5', 1, 8);

INSERT INTO kanji (kanjiindex, kanji, onyomi1, onyomi2, onyomi3, kunyomi1, kunyomi2, kunyomi3,
                   korean_meaning, meaning_description, example1, example2, example3,
                   jlpt_level, sector, index_num)
VALUES ('N5-009', '時', 'ジ', NULL, NULL, 'とき', NULL, NULL,
        '때, 시', '시간, 때를 나타내는 한자', '時間(じかん)', '何時(なんじ)', '時々(ときどき)',
        'N5', 1, 9);

INSERT INTO kanji (kanjiindex, kanji, onyomi1, onyomi2, onyomi3, kunyomi1, kunyomi2, kunyomi3,
                   korean_meaning, meaning_description, example1, example2, example3,
                   jlpt_level, sector, index_num)
VALUES ('N5-010', '分', 'フン', 'ブン', 'ブ', 'わける', 'わかれる', 'わかる',
        '나누다, 분', '나누다, 시간의 분', '分(ふん)', '十分(じゅうぶん)', '半分(はんぶん)',
        'N5', 1, 10);

-- インデックス（検索・統計クエリの高速化）
CREATE INDEX idx_kanji_jlpt   ON kanji (jlpt_level);
CREATE INDEX idx_kanji_sector ON kanji (jlpt_level, sector);
CREATE INDEX idx_kanji_char   ON kanji (kanji);

-- 更新日時の自動更新トリガー
CREATE OR REPLACE TRIGGER trg_kanji_updated_at
BEFORE UPDATE ON kanji
FOR EACH ROW
BEGIN
    :NEW.updated_at := SYSTIMESTAMP;
END;
/


-- =============================================
-- 3. 学習ログテーブル（kanji_log）― 出席判定兼用
-- =============================================
-- ★ 出席基準: その日付に kanji_log のレコードが1件以上 → 出席
-- ★ 別途 attendance テーブルは使用しない
-- ★ jlpt_level / sector カラムを含む（レベル・セクター別集計用）
-- =============================================
CREATE TABLE kanji_log (
    logID      NUMBER    GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    accID      NUMBER    NOT NULL,
    kanjiID    NUMBER    NOT NULL,
    is_correct NUMBER(1) NOT NULL CHECK (is_correct IN (0, 1)),
    studied_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    jlpt_level VARCHAR2(2),
    sector     NUMBER,

    CONSTRAINT fk_log_account FOREIGN KEY (accID)
        REFERENCES account(accID) ON DELETE CASCADE,
    CONSTRAINT fk_log_kanji FOREIGN KEY (kanjiID)
        REFERENCES kanji(kanjiID) ON DELETE CASCADE
);

-- インデックス（出席確認・統計クエリ高速化用）
CREATE INDEX idx_log_acc_date ON kanji_log (accID, TRUNC(studied_at));
CREATE INDEX idx_log_acc      ON kanji_log (accID);
CREATE INDEX idx_log_level    ON kanji_log (accID, jlpt_level);
CREATE INDEX idx_log_sector   ON kanji_log (accID, jlpt_level, sector);


-- =============================================
-- 4. 出席確認クエリ（kanji_log ベース）
-- =============================================

-- [1] 本日の出席確認（accID = 1 の場合）
SELECT COUNT(*) AS today_study
FROM kanji_log
WHERE accID = 1
  AND TRUNC(studied_at) = TRUNC(SYSDATE);

-- [2] 当月の出席日一覧
SELECT DISTINCT EXTRACT(DAY FROM studied_at) AS attended_day
FROM kanji_log
WHERE accID = 1
  AND EXTRACT(YEAR  FROM studied_at) = EXTRACT(YEAR  FROM SYSDATE)
  AND EXTRACT(MONTH FROM studied_at) = EXTRACT(MONTH FROM SYSDATE)
ORDER BY attended_day;

-- [3] 当月の出席日数
SELECT COUNT(DISTINCT TRUNC(studied_at)) AS attend_days
FROM kanji_log
WHERE accID = 1
  AND EXTRACT(YEAR  FROM studied_at) = EXTRACT(YEAR  FROM SYSDATE)
  AND EXTRACT(MONTH FROM studied_at) = EXTRACT(MONTH FROM SYSDATE);



-- =============================================
-- 5. テーブル確認クエリ
-- =============================================
DESC account;
DESC kanji;
DESC kanji_log;

SELECT * FROM account;
SELECT * FROM kanji;
SELECT * FROM kanji_log;
