-- =============================================
-- オボエ（漢字学習Webアプリ）テーブル作成SQL
-- DB: Oracle Database
-- =============================================

-- 1. 会員テーブル
CREATE TABLE account (
    accID      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    userID     VARCHAR2(50)  NOT NULL UNIQUE,
    userPW1    VARCHAR2(100) NOT NULL,
    userPW2    VARCHAR2(100) NOT NULL,
    email      VARCHAR2(100),
    phone      VARCHAR2(20),
    nickname   VARCHAR2(50)  NOT NULL UNIQUE,
    attendance NUMBER DEFAULT 0,
    regDate    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. 漢字テーブル
CREATE TABLE kanji (
    kanjiID             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kanjiindex          VARCHAR2(20),
    kanji               VARCHAR2(10)   NOT NULL,
    onyomi1             VARCHAR2(50),
    onyomi2             VARCHAR2(50),
    onyomi3             VARCHAR2(50),
    kunyomi1            VARCHAR2(50),
    kunyomi2            VARCHAR2(50),
    kunyomi3            VARCHAR2(50),
    korean_meaning      VARCHAR2(200),
    meaning_description VARCHAR2(500),
    example1            VARCHAR2(200),
    example2            VARCHAR2(200),
    example3            VARCHAR2(200),
    jlpt_level          VARCHAR2(5)    NOT NULL,
    sector              NUMBER         NOT NULL,
    index_num           NUMBER         NOT NULL,
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. 学習ログテーブル
CREATE TABLE kanji_log (
    logID      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accID      NUMBER NOT NULL,
    kanjiID    NUMBER NOT NULL,
    is_correct NUMBER(1) DEFAULT 0,
    studied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_log_account FOREIGN KEY (accID)   REFERENCES account(accID),
    CONSTRAINT fk_log_kanji   FOREIGN KEY (kanjiID)  REFERENCES kanji(kanjiID)
);

-- インデックス（統計クエリ高速化用）
CREATE INDEX idx_log_accid ON kanji_log(accID);
CREATE INDEX idx_log_studied ON kanji_log(studied_at);
CREATE INDEX idx_kanji_level ON kanji(jlpt_level, sector);